
#include "programs/battery.h"
#include "programs/c_major.h"
#include "programs/charriots_of_fire.h"
#include "programs/color_mixer.h"
#include "programs/fade.h"
#include "programs/fur_elise.h"
#include "programs/hobbit.h"
#include "programs/light_up_on_movement.h"
#include "programs/percussion.h"
#include "programs/ping.h"
#include "programs/random_flash_on_fall.h"
#include "programs/wild_mountain_thyme.h"
#include "programs/queue.h"

#include "programs/show/the_end.h"
#include "programs/show/intro.h"
