#!/bin/sh +x

uc="m168"
hf=0xd9
prg="avrusb500"

help()
{
	echo "prg_fusebit_uc -- read and write the fuse bits"
	echo ""
	echo "Usage: prg_fusebit_uc [-hu] [-H highfusebyte] -r|-w Freq"
	echo ""
	echo "OPTIONS: -h this help"
	echo "         -r read fuse bytes"
	echo "         -w write fuse bytes such that a given Freq is used"
	echo "            a frequency of 0 means external crystal. Possible"
	echo "            values are 0,1,2,4,8"
	echo "         -H write high fuse byte (0xd9=factory default, 0xc9=full swing high freq)"
	echo ""
	echo "EXAMPLE: program the fuses to 4MHz internal"
	echo "         prg_fusebit_uc -w 4"
}

case $1 in
    -h)
		help
		shift 1
		;;
    -r)
		# Read fuses
		avrdude -p $uc -c $prg -v -q
		echo "Explanation: Fuse Low Byte: 0xe1 (1MHz intern), 0xe3 (4MHz intern), "
		echo "             0xe4 (8MHz intern), 0xee (ext cryst)"
		echo "             Fuse High Byte should be 0xd9 (default) or 0xc9 (full swing)"
		;;
    -w)
		freq="$2"
		case $freq in
			0) lf=0xee;echo "Make sure you have a crystal otherwise you can not change this!";sleep 2;;
			1) lf=0xe1;;
			2) lf=0xe2;;
			4) lf=0xe3;;
			8) lf=0xe4;;
			*) echo "error: no such frequency, -h for help";exit 1;;
		esac
		# Set fuses. First high fuse then low
		avrdude -p $uc -c $prg -u -v -U hfuse:w:$hf:m
		avrdude -p $uc -c $prg -u -v -U lfuse:w:$lf:m
		;;
    -*)
		echo "error: no such option $1. -h for help"
		exit 1
		;;
    *)
		help
		;;
esac

exit 0
